name: Release Drafter

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  release_drafter:
    uses: .github/workflows/release-drafter.yml@v6
